name: GitHub Client Test
on: [ push ]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: read
      contents: read
      deployments: read
      issues: read
      packages: read
      pull-requests: read
      repository-projects: read
      security-events: read
      statuses: read
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: chmod -R 777 *
        run: chmod -R 777 *

      - name: Init gradle project
        run: ./gradlew clean --scan

      - name: Assemble
        run: ./gradlew assemble --scan

      - name: BuildPlugin
        run: ./gradlew buildPlugin

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/mirai/*
